export default {
    "root":[
        {
            name:'首页',
            id:0,
            path:'/home/home'
        },
        {
            name:'设置',
            id:1,
            path:'/home/settings'
        },
        {
            name:'用户管理',
            id:2,
            path:'/home/admin',
            children:[
                {
                    name:'用户添加',
                    id:20,
                    path:'/home/admine/add'
                },
                {
                    name:'管理员管理',
                    id:21,
                    path:'/home/admine/root'
                }
            ]
        },
        {
            name:'图表展示',
            id:3,
            path:'/home/echart',
            children:[
                {
                    name:'饼状图',
                    id:30,
                    path:'/home/echart/bin',
                    children:[
                        {
                            name:'饼状图1',
                            id:301,
                            path:'/home/echart/bin/bin1'
                        },
                        {
                            name:'饼状图2',
                            id:302,
                            path:'/home/echart/bin/bin2'
                        }
                    ]
                },
                {
                    name:'折线图',
                    id:31,
                    path:'/home/echart/line',
                    children:[
                        {
                            name:'折线图1',
                            id:311,
                            path:'/home/echart/line/line1',
                        },
                        {
                            name:'折线图2',
                            id:312,
                            path:'/home/echart/line/line2',
                        }
                    ]
                }
            ]
        }
    ]
}